### PR TITLE
Update muse6582_b2l_l_defconfig

### PR DESCRIPTION
**Pull request by ilhan-athn7**
Fix for errors while compiling.

### CODE REVIEW

**Review by chijure — APPROVED** [review]
all ok 👌

**Comment by ilhan-athn7** [comment]
Huge thanks for keeping this repository, i am still using LG G3 Stylus device, lg no longer provide source code of this model;
Now i have this kernel with RR custom rom :-D

Screenshot_2021-06-27-06-59-07
Screenshot_2021-06-27-06-59-37
Screenshot_2021-06-27-06-59-45
Screenshot_2021-06-27-06-59-54
Screenshot_2021-06-27-07-00-08

All OK 👌, except row schedule, i dont know why it just gave me error while compiling, so i added 
"# CONFIG_IOSCHED_ROW is not set" to fix it, this scheduler not available.

**Comment by chijure** [comment]
> Muchas gracias por mantener este repositorio, todavía estoy usando el dispositivo LG G3 Stylus, LG ya no proporciona el código fuente de este modelo;
> Ahora tengo este kernel con rom personalizada RR :-D
> 
> Screenshot_2021-06-27-06-59-07
> Screenshot_2021-06-27-06-59-37
> Screenshot_2021-06-27-06-59-45
> Screenshot_2021-06-27-06-59-54
> Screenshot_2021-06-27-07-00-08
> 
> Todo bien 👌



> Huge thanks for keeping this repository, i am still using LG G3 Stylus device, lg no longer provide source code of this model;
> Now i have this kernel with RR custom rom :-D
> 
> Screenshot_2021-06-27-06-59-07
> Screenshot_2021-06-27-06-59-37
> Screenshot_2021-06-27-06-59-45
> Screenshot_2021-06-27-06-59-54
> Screenshot_2021-06-27-07-00-08
> 
> All OK 👌

thank you too you, i'm no longer developer for Android System Extreme, but i ever present in github for any questions!!

**Comment by ilhan-athn7** [comment]
Sorry to report this,
The overclocking commit is actually not stable, it somehow degrades the overall performance, so it does its job in the opposite direction.

Anyway, it doesn't matter since it's been 4 years :-)

**Pull request merged**
